### PR TITLE
Update README to mention phi

### PR DESCRIPTION
**Pull request by fate-lovely**
Hi, first, thank you guys for such elegant work :D. I really enjoy using chi to build http service, 
but I prefer fasthttp to net/http, so I port chi to fasthttp, which
named [phi](https://github.com/fate-lovely/phi).

### CODE REVIEW

**Comment by jawnsy** [comment]
@fate-lovely Would it be possible to add fasthttp support to chi somehow? Otherwise, it might be difficult keeping your fork up-to-date with some of the latest changes in chi. This seems, more generally, to be one of the problems with fasthttp: most libraries and frameworks are written to coexist with the standard net/http, thus severely limiting the ecosystem compatible with fasthttp.

**Comment by fate-lovely** [comment]
@jawnsy There seems to be no easy way to add fasthttp support to chi except replace every `http.Handler ` interface to fasthttp request handler, cause go doesn't have generics. I will keep watching chi and update phi, it seems the only way to go😄. I really enjoy fasthttp, not for its performance, but its elegant design. A single `ctx *fasthttp.RequestCtx` is much better and flexible than `(w http.ResponseWriter, r *http.Request)`.

**Comment by pkieltyka** [comment]
thanks. Can you list the project in the table of https://github.com/go-chi/chi#auxiliary-middlewares--packages

**Comment by pkieltyka** [comment]
btw, its not possible to add fasthttp to chi directly, it would create a dependency and major change which goes against the design of the project

**Comment by fate-lovely** [comment]
@pkieltyka It's been moved to the table, please check.

**Pull request merged**
