### PR TITLE
Implemented LOCK and UNLOCK handlers

### PR DESCRIPTION
**Pull request by tboerger**
Fixes https://github.com/go-chi/chi/issues/264

### CODE REVIEW

**Comment by tboerger** [comment]
I have already started to use these changes within my tool and it's working good so far.

**Comment by pkieltyka** [comment]
Hi, I’m on vacation for 2 weeks and won’t be able to help until I return. Just FYI, I have a different solution in mind - specifically in the core I do not want to define unstandard methods like this, however I have a solution that will allow you to add your own methods at runtime. For now just use your fork

**Comment by tboerger** [comment]
Yeah currently I'm using my vendored fork for that. These methods are part of a standard, it's part of the Webdav specification, for reference: http://www.webdav.org/specs/rfc2518.html

**Comment by pkieltyka** [comment]
solved in https://github.com/go-chi/chi/commit/d806569952e5c14126a155fe66cf102139d11979

**Pull request closed without merging**
