### PR TITLE
Keep "/" route in RoutePattern method

### PR DESCRIPTION
**Pull request by luca147**
Issue related: https://github.com/go-chi/chi/issues/816

### CODE REVIEW

**Comment by VojtechVitek** [comment]
Sorry I don't follow the issue. #816 looks to be in DataDog/dd-trace-go?

**Comment by luca147** [comment]
Hi @VojtechVitek ! Yes the issue take place into dd-trace-go, but after upgrade go-chi to 5.0.8

```go
	routePattern := cfg.modifyResourceName(chi.RouteContext(r.Context()).RoutePattern())
	span.SetTag(ext.HTTPRoute, routePattern)
	var resourceName string
	if cfg.resourceNamer != nil {
		resourceName = cfg.resourceNamer(r)
	} else {
		resourceName = routePattern
		if resourceName == "" {
			resourceName = "unknown"
		}
		resourceName = r.Method + " " + resourceName
	}
	span.SetTag(ext.ResourceName, resourceName)
```
https://github.com/DataDog/dd-trace-go/blob/main/contrib/go-chi/chi.v5/chi.go#L77-L89

As you can see, the tracer for chi, get the resourceName from `RoutePattern`, but with the change introduced in 5.0.8 this route is removed by trim call, and we started fall into`resourceName = "unknown"`

I think the root route is valid and must be returned by `RoutePattern`

**Comment by luca147** [comment]
Hello @VojtechVitek if you think this case must be contemplated in dd-trace-go I can close this PR and Issue, but to make it work is a bit hacky due I need to check if the path is '/' to prevent the tracer from not seeing it as an unresolved path.

**Comment by pkieltyka** [comment]
solved in https://github.com/go-chi/chi/commit/f4ab9b1f050bdcf14bd096399e8bd57363406514

**Pull request closed without merging**
